import type { Dict, Lang } from '../platform/i18n';

const ru: Dict = {
  'app.title': 'Дрифт-Легенда',
  'boot.sdk': 'Связь с Яндекс.Играми…',
  'boot.assets': 'Собираем трассу…',
  'boot.ready': 'Готово!',
  'boot.tap': 'Нажмите, чтобы играть',

  'menu.play': 'В ЗАЕЗД',
  'menu.garage': 'Гараж',
  'menu.best': 'Рекорд',
  'menu.shop': 'Лавка',
  'menu.top': 'Топ',
  'menu.daily': 'Награда',
  'menu.settings': 'Настройки',

  'hud.speed': 'км/ч',
  'hud.drift': 'ДРИФТ',
  'hud.nitro': 'НИТРО',
  'hud.checkpoint': 'ЧЕКПОИНТ +{n} с',
  'hud.crash': 'АВАРИЯ',
  'hud.offroad': 'ВЕРНИСЬ НА ТРАССУ',
  'hud.perfect': 'ЧИСТЫЙ ДРИФТ!',

  'race.ready': 'ПРИГОТОВЬСЯ',
  'race.go': 'ПОЕХАЛИ!',
  'race.timeUp': 'Время вышло',

  'result.title': 'Заезд окончен',
  'result.score': 'Очки',
  'result.distance': 'Дистанция',
  'result.drift': 'Лучший множитель',
  'result.coins': 'Монеты',
  'result.newBest': 'НОВЫЙ РЕКОРД!',
  'result.again': 'Ещё заезд',
  'result.garage': 'В гараж',
  'result.x2': 'Удвоить монеты',
  'result.revive': 'Продолжить заезд',
  'result.reviveSub': 'Ещё {n} секунд',
  'result.reviveLeft': 'Осталось продолжений: {n}',

  'garage.title': 'Гараж',
  'garage.sub': 'Прокачай машину и выбери цвет',
  'garage.select': 'Выбрать',
  'garage.selected': 'Выбрана',
  'garage.buy': 'Купить',
  'garage.locked': 'Закрыто',
  'garage.paint': 'Покраска',
  'garage.upgrades': 'Улучшения',
  'upg.engine': 'Двигатель',
  'upg.turbo': 'Разгон',
  'upg.tires': 'Резина',
  'upg.nitro': 'Баллон нитро',
  'upg.max': 'МАКС',
  'upg.level': 'Ур. {n}/{max}',
  'stat.topSpeed': 'Макс. скорость',
  'stat.accel': 'Разгон',
  'stat.grip': 'Сцепление',

  'shop.title': 'Лавка',
  'shop.sub': 'Ускорь прокачку',
  'shop.freeCoins': 'Монеты за рекламу',
  'shop.watch': 'Смотреть',
  'shop.limit': 'Лимит на сегодня',
  'shop.noAds': 'Отключить рекламу',
  'shop.noAdsDesc': 'Убирает баннер и межстраничную рекламу навсегда',
  'shop.noAdsOwned': 'Реклама отключена. Спасибо!',
  'shop.starter': 'Набор новичка',
  'shop.unavailable': 'Покупки недоступны в этой версии',
  'shop.purchased': 'Покупка получена!',
  'shop.failed': 'Покупка отменена',

  'daily.title': 'Ежедневная награда',
  'daily.sub': 'Заходи каждый день, награда растёт',
  'daily.claim': 'Забрать',
  'daily.claimX2': 'Удвоить за рекламу',
  'daily.claimed': 'Уже забрано. Приходи завтра!',
  'daily.streak': 'Серия: {n} дн.',

  'lb.title': 'Таблица лидеров',
  'lb.sub': 'Лучшие дрифтеры',
  'lb.you': 'Вы',
  'lb.unavailable': 'Таблица доступна только внутри Яндекс.Игр',
  'lb.login': 'Войти, чтобы попасть в таблицу',
  'lb.loading': 'Загружаем…',

  'settings.title': 'Настройки',
  'settings.sound': 'Звук',
  'settings.music': 'Музыка',
  'settings.vibro': 'Вибрация',
  'settings.banner': 'Баннер снизу',
  'settings.quality': 'Графика',
  'settings.lang': 'Язык',
  'settings.rate': 'Оценить игру',
  'settings.shortcut': 'Ярлык на рабочий стол',
  'settings.reset': 'Сбросить прогресс',
  'settings.resetConfirm': 'Весь прогресс будет удалён. Точно?',
  'settings.resetYes': 'Да, удалить',
  'settings.version': 'Версия {v}',
  'quality.high': 'Высокая',
  'quality.medium': 'Средняя',
  'quality.low': 'Низкая',

  'levelup.title': 'Уровень {n}!',
  'levelup.reward': 'Награда',

  'tutor.title': 'Как играть',
  'tutor.steer': 'Держи левую или правую половину экрана, чтобы поворачивать',
  'tutor.steerPc': 'Клавиши A и D или стрелки, чтобы поворачивать',
  'tutor.drift': 'Входи в поворот на скорости, машина уйдёт в занос и очки полетят',
  'tutor.nitro': 'Дрифт копит нитро. Жми кнопку, чтобы ускориться',
  'tutor.nitroPc': 'Дрифт копит нитро. Shift, чтобы ускориться',
  'tutor.time': 'Чекпоинты добавляют время. Не врезайся в препятствия',
  'tutor.go': 'Поехали!',

  'ad.failed': 'Реклама не загрузилась, попробуйте позже',
  'ad.noReward': 'Награда не начислена: ролик не досмотрен',
  'ad.wait': 'Подождите немного',

  'common.close': 'Закрыть',
  'common.ok': 'Понятно',
  'common.cancel': 'Отмена',
  'common.on': 'Вкл',
  'common.off': 'Выкл',
  'common.notEnough': 'Не хватает монет',
  'common.m': 'м',
};

const en: Dict = {
  'app.title': 'Drift Legend',
  'boot.sdk': 'Connecting to Yandex.Games…',
  'boot.assets': 'Building the track…',
  'boot.ready': 'Ready!',
  'boot.tap': 'Tap to play',

  'menu.play': 'RACE',
  'menu.garage': 'Garage',
  'menu.best': 'Best',
  'menu.shop': 'Shop',
  'menu.top': 'Top',
  'menu.daily': 'Reward',
  'menu.settings': 'Settings',

  'hud.speed': 'km/h',
  'hud.drift': 'DRIFT',
  'hud.nitro': 'NITRO',
  'hud.checkpoint': 'CHECKPOINT +{n}s',
  'hud.crash': 'CRASH',
  'hud.offroad': 'GET BACK ON TRACK',
  'hud.perfect': 'CLEAN DRIFT!',

  'race.ready': 'READY',
  'race.go': 'GO!',
  'race.timeUp': 'Time up',

  'result.title': 'Run over',
  'result.score': 'Score',
  'result.distance': 'Distance',
  'result.drift': 'Best multiplier',
  'result.coins': 'Coins',
  'result.newBest': 'NEW BEST!',
  'result.again': 'Race again',
  'result.garage': 'Garage',
  'result.x2': 'Double the coins',
  'result.revive': 'Keep driving',
  'result.reviveSub': '{n} more seconds',
  'result.reviveLeft': 'Continues left: {n}',

  'garage.title': 'Garage',
  'garage.sub': 'Upgrade your car and pick a colour',
  'garage.select': 'Select',
  'garage.selected': 'Selected',
  'garage.buy': 'Buy',
  'garage.locked': 'Locked',
  'garage.paint': 'Paint',
  'garage.upgrades': 'Upgrades',
  'upg.engine': 'Engine',
  'upg.turbo': 'Acceleration',
  'upg.tires': 'Tires',
  'upg.nitro': 'Nitro tank',
  'upg.max': 'MAX',
  'upg.level': 'Lv. {n}/{max}',
  'stat.topSpeed': 'Top speed',
  'stat.accel': 'Acceleration',
  'stat.grip': 'Grip',

  'shop.title': 'Shop',
  'shop.sub': 'Speed up your progress',
  'shop.freeCoins': 'Coins for an ad',
  'shop.watch': 'Watch',
  'shop.limit': 'Daily limit reached',
  'shop.noAds': 'Remove ads',
  'shop.noAdsDesc': 'Removes the banner and interstitials forever',
  'shop.noAdsOwned': 'Ads removed. Thank you!',
  'shop.starter': 'Starter pack',
  'shop.unavailable': 'Purchases are unavailable in this build',
  'shop.purchased': 'Purchase granted!',
  'shop.failed': 'Purchase cancelled',

  'daily.title': 'Daily reward',
  'daily.sub': 'Come back every day, rewards grow',
  'daily.claim': 'Claim',
  'daily.claimX2': 'Double with an ad',
  'daily.claimed': 'Already claimed. See you tomorrow!',
  'daily.streak': 'Streak: {n} days',

  'lb.title': 'Leaderboard',
  'lb.sub': 'Best drifters',
  'lb.you': 'You',
  'lb.unavailable': 'The leaderboard only works inside Yandex.Games',
  'lb.login': 'Sign in to join the leaderboard',
  'lb.loading': 'Loading…',

  'settings.title': 'Settings',
  'settings.sound': 'Sound',
  'settings.music': 'Music',
  'settings.vibro': 'Vibration',
  'settings.banner': 'Bottom banner',
  'settings.quality': 'Graphics',
  'settings.lang': 'Language',
  'settings.rate': 'Rate the game',
  'settings.shortcut': 'Add a desktop shortcut',
  'settings.reset': 'Reset progress',
  'settings.resetConfirm': 'All progress will be erased. Are you sure?',
  'settings.resetYes': 'Yes, erase',
  'settings.version': 'Version {v}',
  'quality.high': 'High',
  'quality.medium': 'Medium',
  'quality.low': 'Low',

  'levelup.title': 'Level {n}!',
  'levelup.reward': 'Reward',

  'tutor.title': 'How to play',
  'tutor.steer': 'Hold the left or right half of the screen to steer',
  'tutor.steerPc': 'Use A and D or the arrow keys to steer',
  'tutor.drift': 'Enter corners fast, the car slides and the points roll in',
  'tutor.nitro': 'Drifting fills the nitro tank. Tap the button to boost',
  'tutor.nitroPc': 'Drifting fills the nitro tank. Hold Shift to boost',
  'tutor.time': 'Checkpoints add time. Do not hit the obstacles',
  'tutor.go': 'Let us go!',

  'ad.failed': 'Ad failed to load, try again later',
  'ad.noReward': 'No reward: the video was not watched',
  'ad.wait': 'Please wait a moment',

  'common.close': 'Close',
  'common.ok': 'Got it',
  'common.cancel': 'Cancel',
  'common.on': 'On',
  'common.off': 'Off',
  'common.notEnough': 'Not enough coins',
  'common.m': 'm',
};

const tr: Dict = {
  'app.title': 'Drift Efsanesi',
  'boot.sdk': 'Yandex.Games bağlanıyor…',
  'boot.assets': 'Pist hazırlanıyor…',
  'boot.ready': 'Hazır!',
  'boot.tap': 'Oynamak için dokun',

  'menu.play': 'YARIŞ',
  'menu.garage': 'Garaj',
  'menu.best': 'Rekor',
  'menu.shop': 'Dükkân',
  'menu.top': 'Top',
  'menu.daily': 'Ödül',
  'menu.settings': 'Ayarlar',

  'hud.speed': 'km/s',
  'hud.drift': 'DRIFT',
  'hud.nitro': 'NITRO',
  'hud.checkpoint': 'KONTROL +{n}sn',
  'hud.crash': 'KAZA',
  'hud.offroad': 'PİSTE GERİ DÖN',
  'hud.perfect': 'TEMİZ DRIFT!',

  'race.ready': 'HAZIR',
  'race.go': 'BAŞLA!',
  'race.timeUp': 'Süre doldu',

  'result.title': 'Yarış bitti',
  'result.score': 'Puan',
  'result.distance': 'Mesafe',
  'result.drift': 'En iyi çarpan',
  'result.coins': 'Altın',
  'result.newBest': 'YENİ REKOR!',
  'result.again': 'Tekrar yarış',
  'result.garage': 'Garaj',
  'result.x2': 'Altını ikiye katla',
  'result.revive': 'Devam et',
  'result.reviveSub': '{n} saniye daha',
  'result.reviveLeft': 'Kalan devam hakkı: {n}',

  'garage.title': 'Garaj',
  'garage.sub': 'Arabanı geliştir ve rengini seç',
  'garage.select': 'Seç',
  'garage.selected': 'Seçili',
  'garage.buy': 'Satın al',
  'garage.locked': 'Kilitli',
  'garage.paint': 'Boya',
  'garage.upgrades': 'Geliştirmeler',
  'upg.engine': 'Motor',
  'upg.turbo': 'Hızlanma',
  'upg.tires': 'Lastik',
  'upg.nitro': 'Nitro deposu',
  'upg.max': 'MAKS',
  'upg.level': 'Sv. {n}/{max}',
  'stat.topSpeed': 'Maks. hız',
  'stat.accel': 'Hızlanma',
  'stat.grip': 'Tutuş',

  'shop.title': 'Dükkân',
  'shop.sub': 'Gelişimini hızlandır',
  'shop.freeCoins': 'Reklam karşılığı altın',
  'shop.watch': 'İzle',
  'shop.limit': 'Günlük limit doldu',
  'shop.noAds': 'Reklamları kaldır',
  'shop.noAdsDesc': 'Banner ve geçiş reklamlarını kalıcı kaldırır',
  'shop.noAdsOwned': 'Reklamlar kapalı. Teşekkürler!',
  'shop.starter': 'Başlangıç paketi',
  'shop.unavailable': 'Bu sürümde satın alma yok',
  'shop.purchased': 'Satın alma tamam!',
  'shop.failed': 'Satın alma iptal edildi',

  'daily.title': 'Günlük ödül',
  'daily.sub': 'Her gün gel, ödül büyüsün',
  'daily.claim': 'Al',
  'daily.claimX2': 'Reklamla ikiye katla',
  'daily.claimed': 'Zaten alındı. Yarın gel!',
  'daily.streak': 'Seri: {n} gün',

  'lb.title': 'Liderlik tablosu',
  'lb.sub': 'En iyi drifterlar',
  'lb.you': 'Sen',
  'lb.unavailable': 'Tablo yalnızca Yandex.Games içinde çalışır',
  'lb.login': 'Tabloya girmek için giriş yap',
  'lb.loading': 'Yükleniyor…',

  'settings.title': 'Ayarlar',
  'settings.sound': 'Ses',
  'settings.music': 'Müzik',
  'settings.vibro': 'Titreşim',
  'settings.banner': 'Alt banner',
  'settings.quality': 'Grafik',
  'settings.lang': 'Dil',
  'settings.rate': 'Oyunu puanla',
  'settings.shortcut': 'Masaüstü kısayolu',
  'settings.reset': 'İlerlemeyi sıfırla',
  'settings.resetConfirm': 'Tüm ilerleme silinecek. Emin misin?',
  'settings.resetYes': 'Evet, sil',
  'settings.version': 'Sürüm {v}',
  'quality.high': 'Yüksek',
  'quality.medium': 'Orta',
  'quality.low': 'Düşük',

  'levelup.title': 'Seviye {n}!',
  'levelup.reward': 'Ödül',

  'tutor.title': 'Nasıl oynanır',
  'tutor.steer': 'Dönmek için ekranın sol ya da sağ yarısını basılı tut',
  'tutor.steerPc': 'Dönmek için A ve D ya da ok tuşları',
  'tutor.drift': 'Virajlara hızlı gir, araba kayar ve puanlar akar',
  'tutor.nitro': 'Drift nitro doldurur. Hızlanmak için düğmeye bas',
  'tutor.nitroPc': 'Drift nitro doldurur. Hızlanmak için Shift',
  'tutor.time': 'Kontrol noktaları süre ekler. Engellere çarpma',
  'tutor.go': 'Başlayalım!',

  'ad.failed': 'Reklam yüklenemedi, sonra dene',
  'ad.noReward': 'Ödül yok: video izlenmedi',
  'ad.wait': 'Biraz bekle',

  'common.close': 'Kapat',
  'common.ok': 'Tamam',
  'common.cancel': 'İptal',
  'common.on': 'Açık',
  'common.off': 'Kapalı',
  'common.notEnough': 'Yeterli altın yok',
  'common.m': 'm',
};

export const DRIFT_STRINGS: Record<Lang, Dict> = { ru, en, tr };
